// HOME
export const GET_DECKS_SUCCESS = 'GET_DECKS_SUCCESS';
export const GET_DECKS_FAILED = 'GET_DECKS_FAILED';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export const GET_STATISTICS_FAIL = 'GET_STATISTICS_FAIL';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

// DECK
export const CREATE_DECK_SUCCESS = 'CREATE_DECK_SUCCESS';
export const CREATE_DECK_FAIL = 'CREATE_DECK_FAIL';
export const EDIT_DECK_SUCCESS = 'EDIT_DECK_SUCCESS';
export const EDIT_DECK_FAIL = 'EDIT_DECK_FAIL';

// Deck Detail
export const GET_DECK_SUCCESS = 'GET_DECK_SUCCESS';
export const GET_DECK_FAIL = 'GET_DECK_FAIL';
export const GET_DECK_STATISTICS_SUCCESS = 'GET_DECK_STATISTICS_SUCCESS';
export const GET_DECK_STATISTICS_FAIL = 'GET_DECK_STATISTICS_FAIL';
export const GET_DECK_CARDS_SUCCESS = 'GET_DECK_CARDS_SUCCESS';
export const GET_DECK_CARDS_FAIL = 'GET_DECK_CARDS_FAIL';
export const DELETE_DECK_SUCCESS = 'DELETE_DECK_SUCCESS';
export const DELETE_DECK_FAIL = 'DELETE_DECK_FAIL';
export const UPDATE_DECK_PUBLIC_STATUS_SUCCESS = 'UPDATE_DECK_PUBLIC_STATUS_SUCCESS';
export const UPDATE_DECK_PUBLIC_STATUS_FAIL = 'UPDATE_DECK_PUBLIC_STATUS_FAIL';
export const SELECT_CARD_IN_DECK_DETAILS = 'SELECT_CARD_IN_DECK_DETAILS';
export const UNSELECT_CARD_IN_DECK_DETAILS = 'UNSELECT_CARD_IN_DECK_DETAILS';
export const REMOVE_CARD_SUCCESS = 'REMOVE_CARD_SUCCESS';
export const REMOVE_CARD_FAIL = 'REMOVE_CARD_FAIL';
